### ISSUE TITLE
Please share article configuration

### ISSUE THREAD

**Issue by noemiemoreau** [AIMLab-UBC/VOLTA#1]
Hi,

Thank you for sharing your code.
I was wondering if you could share the parameters' configuration that you used to produce the results of your article.
I am trying to reproduce your results but the configuration given in this git :  `python3 main.py --dataset nucls --image-size 32 --arch resnet18 --workers 2 --epochs 20 --batch-size 256 --lr 0.01 --n_classes 5 --moco-dim 32 --moco-t 0.07 --mlp 32 32 --prediction-head 32 --cos --euclidean-nn --validation-interval 0 --gpu 0 --moco-type maskedenv --patch-size 100 --env-arch resnet18 --mask-ratio 1.2 --env-coef 1.0 --teacher --multi-crop data/nucls ` is very different from the parameters description given in the article. 

Thank you for your help.
Best regards,
Noémie

**Comment by raminnakhli** [comment]
Hi Celestenono,

Thank you for the interest.  The configuration is the same as what was shared in the paper. For the rest of the parameters, you can leave them to the default value. More specifically, you can use the command below; however, note that some parameters might need to be changed for different datasets, as was shared in the paper:

`python train.py <path_to_dataset> --dataset consep --image-size 32 --arch preact_resnet18 --workers 16 --epochs 500 --batch-size 1024 --optim adamw --lr 0.001 --warmup-epoch 10 --weight-decay 0.0001 --dist-backend nccl --dist-url tcp://localhost:10003 --validation-interval 30 --queue-size 65536 --prediction-head 32 --moco-dim 64 --moco-m 0.999 --moco-t 0.07 --mlp 128 --moco-type maskedenv --patch-size 200 --env-arch lambda_resnet26 --mask-ratio 1.2 --env-coef 2.0`.
