### ISSUE TITLE
Request to share model weights

### ISSUE THREAD

**Issue by JAAY-AI** [AIMLab-UBC/VOLTA#2]
Great job！Would the author consider providing trained model weights for segmentation of high-grade serous ovarian cancer cells?

**Comment by raminnakhli** [comment]
Hi @LiuJin629,

Thank you for the interest.  I have uploaded the pretrained weights. You can find them in the `pretrained_weights` folder.

Please note that the model is trained on a collection of ovarian subjects (not solely on the high-grade serous type).

**Comment by JAAY-AI** [comment]
@raminnakhli Thank you very much!

**Comment by florianbuettner** [comment]
Hi @raminnakhli,

inspiring work and thanks for sharing the code!
Downloading the pretrained weigths with git lfs does not work. I get the following message  "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access"...

**Comment by raminnakhli** [comment]
Hi @florianbuettner, thanks for letting me know. I've transferred the files to google drive and updated the main repo page.

Please let me know if you still have issue downloading the weights.

**Comment by florianbuettner** [comment]
Thanks. But these files on google drive do not contain weights but the information for downloading from git lfs.

**Comment by raminnakhli** [comment]
Thanks @florianbuettner. Should be fixed now.
