### ISSUE TITLE
Tutorial on the use of Volta

### ISSUE THREAD

**Issue by petroslk** [AIMLab-UBC/VOLTA#3]
Thank you very much for your interesting and promising research! I have been trying to use your framework but I have been facing some issues with the current level of documentation. Could you provide a simple tutorial on how to run inference on a new dataset? What are the exact HoverNet commands you are using to segment nuclei? And what is the exact structure of the dataset used for training?
It would be really useful for users who want to start with a new set of WSIs, segment nuclei, and train or run inference.

Thanks a lot!

**Comment by raminnakhli** [comment]
Thank you for your interest @petroslk. I have added an inference tutorial notebook to the repo (`volta_inference.ipynb`). 

I also added more instruction on the HoVerNet and dataset preparation steps. As for the HoVerNet, I suggest to refer to the main repo and use the tile-based inference. But for simplicity, here is the command that I used:


```
python run_infer.py \
--gpu='0' \
--nr_types=6 \
--type_info_path=type_info.json \
--batch_size=32 \
--model_mode=fast \
--model_path=pretrained_models/hovernet_fast_pannuke_type_tf2pytorch.tar \
--nr_inference_workers=8 \
--nr_post_proc_workers=16 \
tile \
--input_dir=path_to_folder_containing_all_patches  \
--output_dir=path_to_output_directory \
--mem_usage=0.1 \
--draw_dot \
--save_qupath
```

Please note that you might have to tune the batch-size and number of workers based on your machine.

Hope this helps.

**Comment by feiaaa12345** [comment]
Distributed training consistently shows TCP connection timeout

**Comment by feiaaa12345** [comment]
I have tried not conducting distributed training, and the weights obtained are all 0

**Comment by feiaaa12345** [comment]
Error(s) in loading state_dict for MoCoV3:
Missing key(s) in state_dict
Unexpected key(s) in state_dict

**Comment by raminnakhli** [comment]
Hi @feiaaa12345, 

Thanks for the comment. There are two things to highlight here:
1. since some checkpoints are from multi-gpu training, they have to be converted to single-gpu format before loading. I added this part to the first cell of the inference notebook.
2. checkpoints contain the environment blocks. However, this block is not used during inference. So, during loading, the strict argument has to be set to False. I have addressed this in the notebook too.

Hope this helps. Please let me know if you face any other issues.

**Comment by feiaaa12345** [comment]
Hello, I'd like to ask if I want to train with my own dataset. After running main.py, will I get a pre-trained weight? And then I run volta_inference.ipynb. Is this the correct procedure?

**Comment by raminnakhli** [comment]
Hi @feiaaa12345, yes, that's correct. The training pipelines stores the weights in the location given by the `save-dir` arugment and you can use that checkpoint for `volta_inference.ipynb`.

**Comment by feiaaa12345** [comment]
Thank you very much for your response. I would like to ask another question: If I use my own data, which is divided into three categories: AIS, IAC, and NL, is this the correct way to organize the data before running main.py?
![5e6180904e9ee5288d6f2d97f3f583f](https://github.com/user-attachments/assets/e9d2a1b7-0cc7-4649-aedd-736a5fe26ed7)

**Comment by feiaaa12345** [comment]
If I choose the pre-trained weights hovernet_original_consep_notype_tf2pytorch.tar in the Hovernet model, should I still use 'hovernet' for the --dataset parameter when running convertor.py? Also, what should I use for the --dataset parameter when running main.py?

**Comment by raminnakhli** [comment]
Hi @feiaaa12345, regarding the structure, I would suggest to reformat as below:

data/
├── AIS/
│   ├── train/
│   └── test/
├── IAC/
│   ├── train/
│   └── test/
└── NL/
    ├── train/
    └── test/


Also, for the `convertor.py`, you can use the `hovernet` for the input of the `--dataset` argument. 

If you intend to use a pretrained model, you don't need the `main.py` file as it's used for training purpose only. You can directly use the `volta_inference.ipynb` for inference using the pertained model.

But if you intend to train the model from scratch with your own data, I would suggest that you copy one of the datasets from `dataset` folder ([here](https://github.com/AIMLab-UBC/VOLTA/tree/master/dataset)) and rename it to your own dataset name. You also need to add and import this dataset into the `main.py` file. Then, you can use the dataset name you defined as the input to the `--dataset` argument of the `main.py` file.

Hope this helps.
